name: Checkout Project Directory
inputs:
  project-directory:
    description: 'The repo directory of the project to checkout'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.project-directory }}
      shell: bash
    -   name: Checkout ${{ inputs.project-directory }} directory
        uses: actions/checkout@v4
        with:
            sparse-checkout: ${{ inputs.project-directory }}
            sparse-checkout-cone-mode: false
    -   name: Collapse Parent Directory
        run: rsync --remove-source-files -rP ${{ github.workspace }}/${{ inputs.project-directory }}/ ${{ github.workspace }}/ && rmdir ${{ inputs.project-directory }}