name: Deploy Infrastructure

on:
    push:
        branches: main

concurrency: 
    group: deploy-infra-${{ github.head_ref }}
    cancel-in-progress: true

permissions: read-all

jobs:
    deploy-infra:
        name: Setup AWS Infrastructure
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   run: npm ci

            -   run: ls -la
