name: Deploy Infrastructure

on:
    push:
        branches: main

concurrency: 
    group: deploy-${{ github.head_ref }}
    cancel-in-progress: true

permissions: read-all

jobs:
    deploy:
        name: Setup AWS Infrastructure
        runs-on: ubuntu-latest
        steps:
            -   name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: 18.18.0

            -   name: Checkout Code
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: npm ci
                
            # TODO: This should get moved to a CI flow later
            -   name: Test
                run: npm run test

            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ vars.AWS_REGION }}

            -   name: CDK Diff
                run: ENVIRONMENT=staging npm run diff

            -   name: CDK Deploy
                id: cdk-deploy
                run: |
                    ENVIRONMENT=staging npm run deploy --outputs-file cdk.out.json
                    node --eval "console.log('::set-output name=gateway_url::' + require('./cdk.out.json')['staging-Widgets'].GatewayUrl)"

            -   name: SSM Outputs
                run: echo ${{ steps.cdk-deploy.outputs.gateway_url }}
