name: Deploy Infrastructure

on:
    push:
        branches: main

concurrency: 
    group: deploy-${{ github.head_ref }}
    cancel-in-progress: true

permissions: read-all

jobs:
    deploy:
        name: Setup AWS Infrastructure
        runs-on: ubuntu-latest
        steps:
            -   name: Setup Node
                uses: actions/setup-node@v3
                with:
                    node-version: 18.18.0

            -   name: Checkout Code
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: npm ci

            -   name: Test
                run: npx tsc && npx jest

            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ vars.AWS_REGION }}
            
            -   name: Install AWS CLI
                id: install-aws-cli
                uses: unfor19/install-aws-cli-action@46282f151073130d90347412d9c4ef0640177f22
                with:
                    version: 2

            -   name: CDK Diff
                run: ENVIRONMENT=staging npx cdk diff --require-approval never

            -   name: CDK Deploy
                id: cdk-deploy
                run: |
                    ENVIRONMENT=staging npx cdk deploy --require-approval never --outputs-file cdk.out.json
                    node --eval "console.log('gateway_url=' + require('./cdk.out.json')['staging-Widgets'].GatewayUrl)" >> $GITHUB_OUTPUT

            -   name: Print CDK Outputs
                run: |
                    echo ${{ steps.cdk-deploy.outputs.gateway_url }}

            -   name: Save CDK Outputs to AWS Systems Manager Parameter Store
                run: aws ssm put-parameter \
                        --name /widgets/test \
                        --value ${{ steps.cdk-deploy.outputs.gateway_url }} \
                        --type String \
                        --overwrite

            -   name: Save Artifact
                if: always()
                uses: actions/upload-artifact@v3
                with:
                    name: everything
                    path: |
                        **/*
                        !node_modules