name: Deploy

on:
    push:
        branches:
        - main

concurrency: 
    group: deploy-${{ github.head_ref }}
    cancel-in-progress: true

permissions: read-all

jobs:
    changes:
        name: Check Changes
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.filter.outputs.changes }}
        steps:
        -   uses: actions/checkout@v3
            with:
                fetch-depth: 0
                fetch-tags: false
        -   uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
            id: filter
            with:
                filters: |
                  cdk:
                    - cdk/**
                  doodads:
                    - doodads/**
                  widgets:
                    - widgets/**
    infra:
        name: Setup AWS Infrastructure
        runs-on: ubuntu-latest
        needs: changes
        if: ${{ !cancelled() && contains(needs.changes.outputs.packages, 'cdk') }}
        steps:
        -   uses: ./.github/checkout-project-directory@${{ GITHUB_SHA }}
            with:
                project-directory: cdk
        -   name: Checkout /cdk directory
            uses: actions/checkout@v4
            with:
                sparse-checkout: cdk
                sparse-checkout-cone-mode: false
        -   name: Collapse Parent Directory
            run: rsync --remove-source-files -rP ${{ github.workspace }}/cdk/ ${{ github.workspace }}/ && rmdir cdk
    doodads:
        name: Deploy Doodads
        runs-on: ubuntu-latest
        needs: [changes, infra]
        if: ${{ !cancelled() && contains(needs.changes.outputs.packages, 'doodads') }}
        steps:
        -   name: Checkout /doodads directory
            uses: actions/checkout@v4
            with:
                sparse-checkout: doodads
                sparse-checkout-cone-mode: false
        -   run: ls -la
        -   run: ls -la
            working-directory: ./doodads
    widgets:
        name: Deploy Widgets
        runs-on: ubuntu-latest
        needs: [changes, infra]
        if: ${{ !cancelled() && contains(needs.changes.outputs.packages, 'widgets') }}
        steps:
        -   name: Checkout /widgets directory
            uses: actions/checkout@v4
            with:
                sparse-checkout: widgets
                sparse-checkout-cone-mode: false
        -   run: ls -la
        -   run: ls -la
            working-directory: ./widgets
        